apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: stevendeke/udagram-api-user:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: aws-volume
            mountPath: /root/.aws
        envFrom:
          - configMapRef:
              name: udagram-configmap
          - secretRef:
              name: udagram-secret
      restartPolicy: Always
      volumes:
        - name: aws-volume
          secret:
            secretName: aws-secret
            items:
            - key: credentials
              path: credentials